# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ltntNKXw93B2E7RNubM5tQ6S6KuX0MN
"""

# Thomas Gallardo 3D
# 04 / 10 / 2024
# Programción y Base de Datos

paises = {  # crea un dicionario llamado paises
    'Juan': { 'Chile', 'Argentina' },  # Las claves son nombres de personas y los valores son conjuntos de países que han visitado
    'Pedro': { 'Francia', 'Suiza', 'Chile' },
    'Diego': { 'Chile', 'Italia', 'Francia', 'Perú' },
}

def cuantos_en_comun(a, b): #  Define una función llamada cuantos_en_comun que toma dos parámetros (a y b)
    if a in paises and b in paises: # Verifica si ambas personas (a y b) están presentes en el diccionario paises
        paises_comunes = paises[a].intersection(paises[b]) # Utiliza el método intersection() de los
        #conjuntos para encontrar los países que ambas personas han visitado
        return len(paises_comunes) # Retorna la cantidad de países en común, usando len() para
        # contar los elementos en el conjunto paises_comunes
    else: #  Si alguna de las personas no está en el diccionario, se ejecuta la siguiente línea.
         return 0 # Retorna 0 si alguna de las personas no se encuentra en el diccionario
print(cuantos_en_comun('Juan', 'Diego')) # ejemplos
print(cuantos_en_comun('Diego', 'Pedro'))